var files =
[
    [ "/home/arsene/pd-externals/Fraise/analog/analog.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/core/core.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/core/typedefs.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/crt/__crt.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/dcmotor/dcmotor.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/dmx/dmx.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/dmx_slave/dmx_slave.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/eeparams/eeparams.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/fraisedevice/fraisedevice.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/fruit/fruit.h", "fruit_8h.html", "fruit_8h" ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/i2c_master.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/config.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/i2c.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/int.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/osc.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/serial.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/stdint.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/i2c_master/pic18f_i2c-master/src/timer.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/pid/pid.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/ramp/ramp.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/servo/servo.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/spimaster/spimaster.h", null, null ],
    [ "/home/arsene/pd-externals/Fraise/switch/switch.h", null, null ]
];